config/routes.rb
Rails.application.routes.draw do
  # ネストまだしてないです
  root 'tops#top'
  get '/user_products/:id' => 'user_products#index', as: 'user_products'
  get '/user_product/:id' => 'user_products#show', as: 'user_product'

  patch "/admin_purchases/:id/destroy"=> "admin_purchases#destroy"
  patch "/admin_purchases/:id/shipping_destroy"=> "admin_purchases#shipping_destroy"

  resources :cart_items, only: [:create, :index, :destroy, :update, :show] do
    member do
      get :test
    end
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

 

  resources :users, only: [:create, :show, :edit, :update, :destroy]
  # resources :comments, only: [:create, :destroy]

  resources :purchases, only: [:create, :index, :new]
  resources :favorites, only: [:create, :index, :destroy] do 
    member do
      get :ss
    end
  end
  resources :shipping_addresses, only: [:create, :destroy, :index] do
    member do
      post :add_address
    end
  end
  resources :events, only: [:create, :show, :index]
  resources :song_orders, only: [:create, :update]
  resources :genres, only: [:create, :index, :edit, :update]

  resources :disks, only: [:create, :update, :new]
  resources :songs, only: [:create, :index, :edit, :update]


  resources :user_products, only: [:index]

  resources :admin_users, only: [:index, :show, :destroy, :update]


  resources :admin_purchases, only: [:index, :show]
  get 'admins/top'
  resources :products, only: [:create, :index, :update, :new, :edit, :destroy] do
   resources :comments, only: [:create, :destroy]
end




  # get 'admin_users/index'
  # get 'admin_users/show'
  # get 'admin_songs_order/create'
  # get 'admin_songs_order/update'
  # get 'admin_genres/index'
  # get 'admin_genres/create'
  # get 'admin_genres/update'
  # get 'admin_genres/edit'
  # get 'admin_disks/create'
  # get 'admin_disks/update'
  # get 'admin_products/new'
  # get 'admin_products/create'
  # get 'admin_products/update'
  # get 'admin_products/index'
  # get 'admin_products/edit'
  # get 'admin_songs/create'
  # get 'admin_songs/update'
  # get 'admins/login'

  # get 'admin_purchases/index'
  # get 'admin_purchases/show'
  # get 'tops/top'
  get 'events/index'
  # get 'events/show'
  # get 'events/create'
  # get 'products/index'
  # get 'products/show'
  # get 'shipping_addresses/index'
  # get 'shipping_addresses/create'
  # get 'shipping_addresses/destroy'
  # get 'cart_items/index'
  # get 'cart_items/show'
  # get 'cart_items/create' => 'cat_items#create', as: "test"
  # get 'cart_items/update'
  # get 'cart_items/destroy'
  # get 'favorites/index'
  # get 'favorites/create'
  # get 'favorites/destroy'
  # get 'purchases/index'
  # get 'purchases/new'
  # get 'purchases/create'
  # get 'comments/create'
  # get 'comments/destroy'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # get 'songs/new'
  # get 'products/new'
  # get 'products/index'
  # get 'products/edit'
  # get 'genres/index'
  # get 'genres/edit'
  # get 'user_products/index'
  # get 'user_products/show'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         validates :email, presence: true
         validates :password, presence: true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :product

end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :product
end

app/models/disk.rb
class Disk < ApplicationRecord

	belongs_to :product
	has_many :song_orders, dependent: :destroy, inverse_of: :disk
	accepts_nested_attributes_for :song_orders, allow_destroy: true
	
end

app/models/event.rb
class Event < ApplicationRecord
	
	belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord

belongs_to :user
belongs_to :product

end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :genre_name, uniqueness: true
	has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
	include SearchProduct
	validates :product_name, presence: true
	validates :product_name, uniqueness: true

	attachment :jaket_image
	
    belongs_to :genre
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :cart_items
	has_many :disks, dependent: :destroy, inverse_of: :product
	has_many :events
	accepts_nested_attributes_for :events
	accepts_nested_attributes_for :disks, allow_destroy: true
	
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	include SearchPurchase
	belongs_to :shipping_address
	belongs_to :user

	attachment :jaket_image

	
end

app/models/song.rb
class Song < ApplicationRecord
	validates :song_name, uniqueness: true

	has_many :song_orders
end

app/models/song_order.rb
class SongOrder < ApplicationRecord
	belongs_to :disk
	belongs_to :song
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 	include SearchUser
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :favorites
has_many :comments
has_many :carts
has_many :shipping_addresses
has_many :purchases

attachment :profile_image
attachment :favorite_people_image

validates :user_name, presence: true, length: { maximum: 50 }
validates :user_name_phonetic, presence: true , length: { maximum: 50 } ,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
validates :postal_code, presence: true, length: { is: 7 }
validates :address, presence: true
validates :phone_number, presence: true, length: { is: 11 }
validates :favorite_people, length: { maximum: 150 }




def inactive_message
  !deleted_at ? super : :deleted_account



end

include JpPrefecture
  jp_prefecture :prefecture_code
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


  def soft_delete
    update(deleted_at: Time.now)
  end


def active_for_authentication?
  !deleted_at
end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
  	@user = current_user
  	@users = User.page(params[:page]).per(5).order(:id)
    @aaa = @user.favorites
  end


  def ss
    product = Product.find(params[:id])
    Favorite.find_or_create_by(user_id: current_user.id, product_id: params[:id])

    redirect_back(fallback_location: user_product_path)
  end

  def create
  end

  def destroy
  end

private
def favorite_params
  params.require(:favorite).permit(:user_id, :product_id, :cart_item, :number_of_sheets, :old_price, :jaket_image_id, :label_name, :product_name)
end


end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disks_helper.rb
module DisksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/index.html.erb
<%= render 'layouts/header' %>
<body>
    <div class="container">
      <div class="row">
        <div class="col-xs-3">
                <div class="mypage_sidebar">
                    <div class="sidelink1">MENU</div>
                        <%= link_to "HOME",root_path, class: "sidelink"%>
                        <%= link_to "お気に入り",favorites_path(current_user), class: "sidelink"%>
                        <%= link_to "購入履歴",purchases_path(current_user), class: "sidelink"%>
                        <%= link_to "所持チケット",events_path(current_user), class: "sidelink"%>
                        <%= link_to '退会手続き',current_user, method: :delete, data: {confirm: '本当に退会しますか?'},class: "sidelink" %>
                        <style type="text/css">
                              a.sidelink { display: block; }
                        </style>
                </div>
        </div>

            <div class="col-xs-9">
              <% @aaa.each do |favorite|%>
              <div class="fp">
                <div class="jki">

                  <%= attachment_image_tag favorite.product, :jaket_image, :fill, 150, 150 %>
                </div>

                          <table class="favorite_information">
                            <thead>
                              <tr>
                              <th class="space" style="width:200px;"></th>
                              <th></th>
                              <th></th>
                              </tr>
                            </thead>

                            <tbody>
                              <tr>
                                <th>CD名</th>
                                <td class="favorite_td" , style="text-align: left;"><%= favorite.product.product_name %></td>
                              </tr>

                              <tr>
                                <th>アーティスト名</th>
                                <td class="favorite_td" , style="text-align: left;"><%= favorite.product.airtist_name %></td>
                              </tr>

                              <tr>
                                <th>特典</th>
                                <td class="favorite_td" , style="text-align: left;">あり</td>
                              </tr>

                              <tr>
                                <th>評価</th>
                                <td class="favorite_td" , style="text-align: left;">♡♡♡</td>
                                <th>在庫</th>
                                <td class="favorite_td" , style="text-align: left;"><%= favorite.product.stock %></td>
                              </tr>


                            </tbody>
                          </table>


              </div>
              <% end %>


                

            </div>
        </div>
    </div>
</body>