config/routes.rb
Rails.application.routes.draw do
  # ネストまだしてないです
  root 'tops#top'
  get '/user_products/:id' => 'user_products#index', as: 'user_products'
  get '/user_product/:id' => 'user_products#show', as: 'user_product'

  patch "/admin_purchases/:id/destroy"=> "admin_purchases#destroy"
  patch "/admin_purchases/:id/shipping_destroy"=> "admin_purchases#shipping_destroy"

  resources :cart_items, only: [:create, :index, :destroy, :update, :show] do
    member do
      get :test
    end
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

 

  resources :users, only: [:create, :show, :edit, :update, :destroy]
  # resources :comments, only: [:create, :destroy]

  resources :purchases, only: [:create, :index, :new]
  resources :favorites, only: [:create, :index, :destroy] do 
    member do
      get :ss
    end
  end
  resources :shipping_addresses, only: [:create, :destroy, :index] do
    member do
      post :add_address
    end
  end
  resources :events, only: [:create, :show, :index]
  resources :song_orders, only: [:create, :update]
  resources :genres, only: [:create, :index, :edit, :update]

  resources :disks, only: [:create, :update, :new]
  resources :songs, only: [:create, :index, :edit, :update]


  resources :user_products, only: [:index]

  resources :admin_users, only: [:index, :show, :destroy, :update]


  resources :admin_purchases, only: [:index, :show]
  get 'admins/top'
  resources :products, only: [:create, :index, :update, :new, :edit, :destroy] do
   resources :comments, only: [:create, :destroy]
end




  # get 'admin_users/index'
  # get 'admin_users/show'
  # get 'admin_songs_order/create'
  # get 'admin_songs_order/update'
  # get 'admin_genres/index'
  # get 'admin_genres/create'
  # get 'admin_genres/update'
  # get 'admin_genres/edit'
  # get 'admin_disks/create'
  # get 'admin_disks/update'
  # get 'admin_products/new'
  # get 'admin_products/create'
  # get 'admin_products/update'
  # get 'admin_products/index'
  # get 'admin_products/edit'
  # get 'admin_songs/create'
  # get 'admin_songs/update'
  # get 'admins/login'

  # get 'admin_purchases/index'
  # get 'admin_purchases/show'
  # get 'tops/top'
  get 'events/index'
  # get 'events/show'
  # get 'events/create'
  # get 'products/index'
  # get 'products/show'
  # get 'shipping_addresses/index'
  # get 'shipping_addresses/create'
  # get 'shipping_addresses/destroy'
  # get 'cart_items/index'
  # get 'cart_items/show'
  # get 'cart_items/create' => 'cat_items#create', as: "test"
  # get 'cart_items/update'
  # get 'cart_items/destroy'
  # get 'favorites/index'
  # get 'favorites/create'
  # get 'favorites/destroy'
  # get 'purchases/index'
  # get 'purchases/new'
  # get 'purchases/create'
  # get 'comments/create'
  # get 'comments/destroy'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # get 'songs/new'
  # get 'products/new'
  # get 'products/index'
  # get 'products/edit'
  # get 'genres/index'
  # get 'genres/edit'
  # get 'user_products/index'
  # get 'user_products/show'
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :product

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def index
      @cart = current_user.carts.where(delete_flag: false).first
      @cart_items = @cart.cart_items
      @price = 0
      @cart_items.each do |cart_item|
        @all_price = cart_item.product.price * cart_item.number_of_sheets
        @price +=  @all_price
      end
  end

  def show
      @cart = current_user.carts.where(delete_flag: false).first
      @cart_items = @cart.cart_items
      @price = 0
      @cart_items.each do |cart_item|
        @all_price = cart_item.product.price * cart_item.number_of_sheets
        @price +=  @all_price
      end
       @shipping_address = current_user.shipping_addresses
       @purchase = Purchase.new
       @cart = current_user.carts.where(delete_flag: false).first
       @cart_items = @cart.cart_items.all
       @shipping_addressA = ShippingAddress.new


  end

  def update
    puts params[:cart_item][:number_of_sheets] #パラメーターを持ってきてこれるか確認するための記述
    puts params[:cart_item][:old_price]
    puts params[:id]
      cart = current_user.carts.where(delete_flag: false).first
      cart_item = CartItem.find(params[:id])
      cart_item.update(number_of_sheets: params[:cart_item][:number_of_sheets], old_price: (params[:cart_item][:number_of_sheets].to_i * params[:cart_item][:old_price].to_i))
      redirect_to cart_items_path
  end
      #puts cart_item.errors.full_messages


  def test #←カートアイテム作成
    product = Product.find(params[:id])
   CartItem.find_or_create_by(cart_id: current_user.carts.where(delete_flag: false).first.id, product_id: params[:id], old_price: product.price)
    redirect_back(fallback_location: user_product_path)
  end

  def create
    purchase = Parchase.find(params[:id])
    purchase.save
    redirect_to cart_items_path
  end


  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path
  end




   private
def cart_item_params
  params.require(:cart_item).permit(:user_id, :product_id, :cart_item, :number_of_sheets, :old_price, :jaket_image, :label_name)
end


end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/destroy.html.erb
<h1>CartItems#destroy</h1>
<p>Find me in app/views/cart_items/destroy.html.erb</p>

app/views/cart_items/index.html.erb
<%= render 'layouts/header' %>  

<body>
  <div class="container" style="margin: 50px;">
    <div class="row">
      <div class="col-lg-10">
      <% @cart_items.each do |cart_item| %>
        <div class="product_show" style="width: 100%; height: 360px; background-color: #ffffff; border: solid 1px #f5f5f5; margin-bottom: 10px;">
		  <div class="container">
		    <div class="row show1">
		      <div class="col-lg-3  cart_item" style="margin: 20px 10px 20px 0px;">
		      	<% if cart_item.product.stock == 0  %>
					<%= image_tag ("soldout.jpg") %>
				<% else %>
					<%= attachment_image_tag cart_item.product, :jaket_image %>
				<% end %>  
		      </div>

			  <div class="col-lg-4">
		        <ul class="list-inline" style="margin: 10px 5px;">
		        <%= link_to (cart_item_path(cart_item.id)), class: "linkb" do %>
		          <li><strong class="h3">商品名: <%= cart_item.product.product_name %></strong></li>
		        <% end %>
		        </ul>

		        <ul class="list-inline" style="margin: 0;">
		          <li><strong class="h3">アーティスト: </strong></li>
		          <li class="h3"><%= cart_item.product.airtist_name %></li>
		         </ul>

		         <ul class="list-inline" style="margin: 10px 5px;">
		           <li><strong class="h3">特典:</strong></li>
		           <li class="h3 text-danger">プレミアムチケット付き</li>
		         </ul>

		         <ul class="list-inline" style="margin: 0;">
		           <li><strong class="h3">評価</strong></li>
		           <li class="h3"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span><span class="glyphicon glyphicon-heart" aria-hidden="true">  </span><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
		           </li>
		         </ul>

		         <ul class="list-inline" style="margin: 15px 5px;">
	          	   <li><strong class="h3">価格:</strong></li>
	          	   <li class="h3"><strong class="h3">￥</strong></li>
	          	   <li class="h3"><%= cart_item.product.price * cart_item.number_of_sheets %></li>
			     </ul>
			  </div>

			   <div class="col-lg-2">
			   	<ul>
			     <li style="list-style: none; margin: 10px 0px 20px 0px;">
			     	<%= link_to (cart_item_path(cart_item.id)), class: "linkb", method: :delete do %>
			     	<p><input type="button" value="カートから削除する" onClick="disp()"></p>
			     	<% end %>
			     </li>
			    </ul>

			     	<%= form_for(cart_item) do |f| %>

			     	<label>枚数</label>
			     	<label><%= f.number_field :number_of_sheets, max: cart_item.product.stock , min: 0 , value: cart_item.number_of_sheets %></label>
			     	<%= f.hidden_field :old_price, value: cart_item.product.price %>
			     	<%= f.submit "決定" %>
			     	<% end %>

			   </div>
	       	</div>
	      </div>
	    </div>
	   <% end %>
        <div style="margin-left: 500px;">
          <form class="form-inline h3">
          	<span>商品合計金額￥：</span>
          	<span>💛</span>
			<span> <%= @price %></span>
          </form>
        </div>
      </div>
	  <div class="col-lg-2 side_ber" style="height: 280px;">
	    <div class="">
	
	         <%= link_to cart_item_path(current_user), class: "linkb" do %>
	      <li class="botan" style="list-style: none; margin: 70px 0px 20px 0px;">
	      	<div>購入ページに進む</div>
	      </li>
	         <% end %>
	
      <%= link_to (root_path), class: "linkb" do %>
		  <li class="botan" style="list-style: none;">
		  	 <div>ショッピングを続ける</div>
		  </li>
	 <% end %>
        </div>
	  </div>
	</div>
  </div>
  
</body>

<%= render 'layouts/footer' %>

app/views/cart_items/show.html.erb
<%= render 'layouts/header' %>

<body>
	<div style="background-color: #FFFF99;, width: 100%;">
			  		<p>購入情報を選択してね！！</p>
			  	</div>
	<div>
		<div Class="box2">
        <%= form_for(@purchase, url: {controller: "purchases", action: "create"}) do |f| %>
		    <div >
		      	<div style="margin-left: 100px;"><%= f.label :"配送先の選択" %></div>
	           <div style="margin-left: 100px;"> <%= f.collection_select(:shipping_address_id, @shipping_address, :id, :shipping_address_name, { autofocus: 'true', class: "form-control"}) %></div>
	        </div>

	        <div >
		        	<div style="margin-left: 100px;"><%= f.label :"支払い方法の選択" %></div>
		        	<div style="margin-left: 100px;"><%= f.select :method_of_payment, [["現金", "現金"], ["クレジット", "クレジット"]], { autofocus: 'true', class: "form-control"} %></div>
		    </div>
		    <div style="margin: 50px 0px 15px 1000px;">
                  <button type="button"><%= f.submit '購入' %></button>
	        </div>
	    </div>
	<% end %>
		<div>
			  <%= form_for(@shipping_addressA, url: {controller: "shipping_addresses", action: "add_address"}) do |f| %>
			  <div class="row">
			  	<div style="background-color: #FFFF99;, width: 100%; padding-left: 20px;">
			  		<p>配送先を追加したい場合はこちら</p>
			  	</div>
	          	<div class="col-sm-2 h4"><strong>配送先追加</strong></div>
	          	<%= f.text_field :shipping_address_name %>
	          <%= f.submit '決定' %>
	            </div>
	          <% end %>
		</div>

	    <div>
		  <table class="table">
			<tr style="background-color: #FFFF99">
              <th class="h2" style="width: 200px; padding-left: 150px;">商品名</th>
              <th class="h2" style="width: 200px; padding-left: 150px;">数量</th>
              <th class="h2" style="width: 200px; padding-left: 135px;">金額</th>
			</tr>
			<% @cart_items.each do |cart_item| %>
			<tr>
				<td class="h3" style="width: 200px; padding-left: 120px;"><%= cart_item.product.product_name %></td>
				<td class="h3" style="width: 200px; padding-left: 120px;"><%= cart_item.number_of_sheets %>枚</td>
				<td class="h3" style="width: 200px; padding-left: 120px;"><%= cart_item.product.price * cart_item.number_of_sheets %>円</td>
			</tr>
			<% end %>
		  </table>
	    </div>
	    <div class= "h3" style="margin: 15px 0px 15px 800px;">
	      <span>商品合計金額￥：</span>
          	<span>💛</span>
			<span> <%= @price %>円</span>
	    </div>
    </div>
   
</body>

<%= render 'layouts/footer' %>