config/routes.rb
Rails.application.routes.draw do
  # ネストまだしてないです
  root 'tops#top'
  get '/user_products/:id' => 'user_products#index', as: 'user_products'
  get '/user_product/:id' => 'user_products#show', as: 'user_product'

  patch "/admin_purchases/:id/destroy"=> "admin_purchases#destroy"
  patch "/admin_purchases/:id/shipping_destroy"=> "admin_purchases#shipping_destroy"

  resources :cart_items, only: [:create, :index, :destroy, :update, :show] do
    member do
      get :test
    end
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

 

  resources :users, only: [:create, :show, :edit, :update, :destroy]
  # resources :comments, only: [:create, :destroy]

  resources :purchases, only: [:create, :index, :new]
  resources :favorites, only: [:create, :index, :destroy] do 
    member do
      get :ss
    end
  end
  resources :shipping_addresses, only: [:create, :destroy, :index] do
    member do
      post :add_address
    end
  end
  resources :events, only: [:create, :show, :index]
  resources :song_orders, only: [:create, :update]
  resources :genres, only: [:create, :index, :edit, :update]

  resources :disks, only: [:create, :update, :new]
  resources :songs, only: [:create, :index, :edit, :update]


  resources :user_products, only: [:index]

  resources :admin_users, only: [:index, :show, :destroy, :update]


  resources :admin_purchases, only: [:index, :show]
  get 'admins/top'
  resources :products, only: [:create, :index, :update, :new, :edit, :destroy] do
   resources :comments, only: [:create, :destroy]
end




  # get 'admin_users/index'
  # get 'admin_users/show'
  # get 'admin_songs_order/create'
  # get 'admin_songs_order/update'
  # get 'admin_genres/index'
  # get 'admin_genres/create'
  # get 'admin_genres/update'
  # get 'admin_genres/edit'
  # get 'admin_disks/create'
  # get 'admin_disks/update'
  # get 'admin_products/new'
  # get 'admin_products/create'
  # get 'admin_products/update'
  # get 'admin_products/index'
  # get 'admin_products/edit'
  # get 'admin_songs/create'
  # get 'admin_songs/update'
  # get 'admins/login'

  # get 'admin_purchases/index'
  # get 'admin_purchases/show'
  # get 'tops/top'
  get 'events/index'
  # get 'events/show'
  # get 'events/create'
  # get 'products/index'
  # get 'products/show'
  # get 'shipping_addresses/index'
  # get 'shipping_addresses/create'
  # get 'shipping_addresses/destroy'
  # get 'cart_items/index'
  # get 'cart_items/show'
  # get 'cart_items/create' => 'cat_items#create', as: "test"
  # get 'cart_items/update'
  # get 'cart_items/destroy'
  # get 'favorites/index'
  # get 'favorites/create'
  # get 'favorites/destroy'
  # get 'purchases/index'
  # get 'purchases/new'
  # get 'purchases/create'
  # get 'comments/create'
  # get 'comments/destroy'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # get 'songs/new'
  # get 'products/new'
  # get 'products/index'
  # get 'products/edit'
  # get 'genres/index'
  # get 'genres/edit'
  # get 'user_products/index'
  # get 'user_products/show'
end

app/models/product.rb
class Product < ApplicationRecord
	include SearchProduct
	validates :product_name, presence: true
	validates :product_name, uniqueness: true

	attachment :jaket_image
	
    belongs_to :genre
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :cart_items
	has_many :disks, dependent: :destroy, inverse_of: :product
	has_many :events
	accepts_nested_attributes_for :events
	accepts_nested_attributes_for :disks, allow_destroy: true
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
    @event = @product.events.build
    @disk = @product.disks.build
    @song_order = @disk.song_orders.build
    @genres = Genre.all
    @songs = Song.all
    @song = Song.new
    
  end

  def create
    product = Product.new(product_params)
    if product.save
      flash[:notice] = "Product was successfully created."
      redirect_to new_product_path
    else
      flash[:notice] = "!!This product already exists or There is no product name!!"
      redirect_to new_product_path
    end
  end

  def index
      @products = Product.page(params[:page]).order(sort_column + ' ' + sort_direction).per(15)
      @products = @products.search(s_title: params[:s_title]) if params[:s_title].present?

  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
    @songs = Song.all
  end


  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product was successfully created."
      redirect_to edit_product_path(@product.id)
    else
      flash[:notice] = "!!This product already exists or There is no product name!!"
      redirect_to edit_product_path(@product.id)
    end
  end

  def destroy
   @product = Product.find(params[:id])
   @product.update(delete_flag: true)
   redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:product_name, :airtist_name, :genre_id, :jaket_image, :price, :label_name, :stock, :delete_flag, disks_attributes: [:id, :disk_name, :_destroy, song_orders_attributes: [:id, :song_id, :disk_id, :song_order_number, :_destroy]], events_attributes: [:id, :event_name, :event_information, :venue, :date_and_time])
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end

  def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_disk_fields.html.erb
				<div class="nested-fields">
					<div class="form-group">
						<%= f.label :disk_name, "ディスク名:", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :disk_name, :placeholder => "ディスク名"%>
						</div>
					</div>

    				<%= f.fields_for :song_orders do |song_order| %>
          				<%= render 'song_order_fields', f: song_order %>
					<% end %>
					<div class="links">
						<%= link_to_add_association "曲を追加", f, :song_orders %>
					</div>
					<%= link_to_remove_association "ディスクを削除", f %><br>
				</div>

app/views/products/_song_order_fields.html.erb
					<div class="nested-fields">
						<div class="form-group">
							<%= f.label :song_order_number, "曲順：", class:"col-lg-3 control-label" %>
							<div class="col-lg-9">
								<%= f.text_field :song_order_number, :placeholder => "曲順"%>
							</div>
						</div>

						<div class="form-group">
							<%= f.label :song_id, "曲名：", class:"col-lg-3 control-label"  %>
							<div class="col-lg-9">
								<%= f.collection_select :song_id, @songs, :id, :song_name, {}, {class: 'js-searchable'} %>
	 						</div>
						</div>
						<%= link_to_remove_association "曲を削除", f %><br>
					</div>

app/views/products/edit.html.erb
<%= render 'layouts/admin' %>


			<div class="col-lg-9">
				<h1 class="product_title">商品編集</h1>
				<% if flash[:notice] %>
					<div class="flash">
						<%= flash[:notice] %>
					</div>
				<% end %>
				<button type="submit" class="btn btn-default", style="margin-bottom: 20px;"><%= link_to "この商品を削除する", product_path(@product.id), method: :delete, "data-confirm" => "Are you sure?" %></button>
				<%= form_for(@product) do |f| %>

					<div class="form-group">
						<%= f.label :product_name, "商品名:", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :product_name, :placeholder => "商品名"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :artist_name, "アーティスト名：", class:"col-lg-3 control-label"  %>
						<div class="col-lg-9">
							<%= f.text_field :airtist_name, placeholder: "アーティスト名"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :genre_id, "ジャンル：", class:"col-lg-3 control-label"  %>
						<div class="col-lg-9">
							<%= f.collection_select :genre_id, @genres, :id, :genre_name, {}, {class: 'js-searchable'} %>
 						</div>
					</div>

					<div class="form-group">
						<%= f.label :label_name, "レーベル名：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :label_name, :placeholder => "レーベル名"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :jaket_image, "商品画像：", class:"col-lg-3 control-label"  %>
				        <div class="col-lg-9">
				        	 <%= f.attachment_field :jaket_image %>
				    	</div>
				    </div>

					<div class="form-group">
						<%= f.label :price, "料金：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :price, :placeholder => "料金"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :stock, "在庫数：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :stock, :placeholder => "在庫数"%>
						</div>
					</div>


    				<%= f.fields_for :events do |event| %>
					<div class="form-group">
						<%= event.label :event_name, "イベント名：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= event.text_field :event_name, :placeholder => "イベント名"%>
						</div>
					</div>

					<div class="form-group">
						<%= event.label :date_and_time, "イベント日時：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= event.text_field :date_and_time, :placeholder => "イベント日時"%>
						</div>
					</div>

					<div class="form-group">
						<%= event.label :venue, "イベント会場：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= event.text_field :venue, :placeholder => "イベント会場"%>
						</div>
					</div>

					<div class="form-group">
						<%= event.label :event_information, "イベント詳細：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= event.text_area :event_information, class:"col-lg-9", style:"height: 100px;"%>
						</div>
					</div>
					<% end %>






				<%= f.fields_for :disks do |disk| %>

          			<%= render 'disk_fields', f: disk %>

				<% end %>
				<div class="links">
					<%= link_to_add_association "ディスクを追加", f, :disks %>
				</div>







					<div class="form-group">
						<div class=" col-lg-9">
							<%= f.submit "商品を編集", class:"btn btn-primary btn-block", style:"margin-bottom: 30px;" %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/products/index.html.erb
<%= render 'layouts/admin' %>


			<div class="col-lg-9">
				<h1 class="product_title">商品一覧</h1>
			        <div class="search">
			          <form action="<%= products_path %>" method="get" class="form-inline">
			            <input type="text" id="search__bar" name="s_title" required size="10" placeholder=" 商品名で検索" value="<%= request[:s_title] %>">
			              <button  class="search__box" type="submit">
			                  <span class="search__box__txt" ><%= image_tag "search.png", alt:"" %> 検索</span>
			              </button>
			          </form>
			        </div>
					<div class="form-group sort">
						<label class="sr-only" for="InputSelect">並び替え</label>
						<select class="form-control" style="width: 70px;" id="InputSelect">
							<option>降順</option>
							<option>昇順</option>
						</select>
					</div>
				<table  class="table table-striped">
					<thead>
						<tr>
							<th>商品ID</th>
							<th>商品名</th>
						</tr>
					</thead>
					<tbody>
					<% @products.where(delete_flag: false).each do |product| %>
						<tr>
							<td>
								<%= product.id %>
							</td>
							<td>
								<%= link_to product.product_name, edit_product_path(product.id) %>
							</td>
						</tr>
					<% end %>
					</tbody>
				</table>
				<nav>
				<%= paginate @products, class:"pagenate" %>
				</nav>
			</div>
		</div>
	</div>

<script>
    if (location.href == "http://localhost:3000/products?direction=asc&sort=id") {
        $('.form-control').html("<option>昇順</option><option>降順</option>");
    }
    if (location.href == "http://localhost:3000/products?direction=asc&sort=id" || location.href == "http://localhost:3000/products?direction=dec&sort=id" || location.href == "http://localhost:3000/products") {
        $('select[class=form-control]').change(function() {
            if ($(this).val() == '降順') {
                window.location.href = "http://localhost:3000/products?direction=dec&sort=id";
            } else {
                window.location.href = "http://localhost:3000/products?direction=asc&sort=id";
            }
        });
    }
</script>

app/views/products/new.html.erb
<%= render 'layouts/admin' %>

			<div class="col-lg-9">
				<h1 class="product_title">商品登録</h1>
				<% if flash[:notice] %>
					<div class="flash">
						<%= flash[:notice] %>
					</div>
				<% end %>
				<%= form_for(@product) do |f| %>

					<div class="form-group" style="margin-top: 50px">
						<%= f.label :product_name, "商品名:", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :product_name, :placeholder => "商品名"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :artist_name, "アーティスト名：", class:"col-lg-3 control-label"  %>
						<div class="col-lg-9">
							<%= f.text_field :airtist_name, placeholder: "アーティスト名"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :genre_id, "ジャンル：", class:"col-lg-3 control-label"  %>
						<div class="col-lg-9">
							<%= f.collection_select :genre_id, @genres, :id, :genre_name, {}, {class: 'js-searchable'} %>
 						</div>
					</div>

					<div class="form-group">
						<%= f.label :label_name, "レーベル名：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :label_name, :placeholder => "レーベル名"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :jaket_image, "商品画像：", class:"col-lg-3 control-label"  %>
				        <div class="col-lg-9">
				        	 <%= f.attachment_field :jaket_image %>
				    	</div>
				    </div>
				    

					<div class="form-group">
						<%= f.label :price, "料金：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :price, :placeholder => "料金"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :stock, "在庫数：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= f.text_field :stock, :placeholder => "在庫数"%>
						</div>
					</div>


    				<%= f.fields_for :events do |events_f| %>
					<div class="form-group">
						<%= f.label :event_name, "イベント名：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= events_f.text_field :event_name, :placeholder => "イベント名"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :date_and_time, "イベント日時：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= events_f.text_field :date_and_time, :placeholder => "イベント日時"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :venue, "イベント会場：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= events_f.text_field :venue, :placeholder => "イベント会場"%>
						</div>
					</div>

					<div class="form-group">
						<%= f.label :event_information, "イベント詳細：", class:"col-lg-3 control-label" %>
						<div class="col-lg-9">
							<%= events_f.text_area :event_information, class:"col-lg-9", style:"height: 100px;"%>
						</div>
					</div>
					<% end %>






				<%= f.fields_for :disks do |disk| %>

          			<%= render 'disk_fields', f: disk %>

				<% end %>
				<div class="links">
					<%= link_to_add_association "ディスクを追加", f, :disks %>
				</div>







					<div class="form-group">
						<div class=" col-lg-9">
							<%= f.submit "商品を登録", class:"btn btn-primary btn-block", style:"margin-bottom: 30px;" %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</body>